workflows:
  ios-dev-build:
    name: iOS Development Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Bundle ID
        BUNDLE_ID: "com.gilad.pklGuide"
        # Your Apple ID email
        APP_STORE_CONNECT_APPLE_ID: "giladsh22@gmail.com"

    scripts:
      # התקנת Flutter dependencies
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      # עדכון Bundle ID
      - name: Set Bundle ID
        script: |
          cd ios
          agvtool new-version -all $(($BUILD_NUMBER + 1))
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = '"$BUNDLE_ID"';/g' Runner.xcodeproj/project.pbxproj

      # התקנת CocoaPods
      - name: Install pods
        script: |
          cd ios && pod install

      # בנייה עם Automatic Code Signing
      - name: Flutter build ipa
        script: |
          cd $CM_BUILD_DIR
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true