workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key #1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gilad.pklGuide
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Flutter build IPA
        script: |
          flutter build ipa --release \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "com.gilad.pklGuide" 2>/dev/null || echo 0) + 1))

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true