workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
          flutter clean
          flutter pub get

      - name: Create certificate if needed
        script: |
          # Codemagic יוצר Certificate אוטומטית!
          keychain initialize
          
          # יצירת private key
          PRIVATE_KEY_PATH=$(mktemp)
          ssh-keygen -t rsa -b 2048 -m PEM -f $PRIVATE_KEY_PATH -q -N ""
          
          # יצירת CSR
          CSR_PATH=$(mktemp)
          openssl req -new -key $PRIVATE_KEY_PATH -out $CSR_PATH \
            -subj "/CN=Codemagic Distribution/C=US/O=Codemagic"
          
          # יצירת Certificate דרך Apple API
          echo "Creating distribution certificate..."
          app-store-connect certificates create \
            --type IOS_DISTRIBUTION \
            --certificate-signing-request @file:$CSR_PATH \
            --private-key @file:$PRIVATE_KEY_PATH \
            --save || echo "Certificate might already exist"
          
          # יצירת Provisioning Profile
          echo "Creating provisioning profile..."
          app-store-connect provisioning-profiles create \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --profile-name "Codemagic PKL Guide" \
            --certificate-resource-id "@all" \
            --save || echo "Profile might already exist"
          
          # הורדת הכל
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --certificate-key @file:$PRIVATE_KEY_PATH \
            --create
          
          keychain add-certificates
          xcode-project use-profiles

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      - name: Flutter build IPA
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" 2>/dev/null || echo 0) + 1))
          
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true