workflows:
  ios-dev-build:
    name: iOS Development Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
        APP_STORE_CONNECT_APPLE_ID: "giladsh22@gmail.com"

    scripts:
      # התקנת Flutter dependencies
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      # חשוב! יצירת קבצי Flutter iOS לפני CocoaPods
      - name: Flutter precache and prepare iOS
        script: |
          flutter precache --ios
          cd ios
          flutter pub get
          cd ..
          flutter build ios-framework --output=ios/Flutter/Generated.xcconfig || true

      # עדכון Bundle ID
      - name: Set Bundle ID
        script: |
          cd ios
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      # התקנת CocoaPods - אחרי שיש את כל קבצי Flutter
      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod install

      # בנייה בלי code signing לבינתיים
      - name: Flutter build iOS
        script: |
          cd $CM_BUILD_DIR
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/**/*.app
      - build/ios/iphonesimulator/**/*.app
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true