workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - default  # הוספתי את זה!
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Create and fetch signing files
        script: |
          # אתחול keychain
          keychain initialize
          
          # יצירת certificate private key חדש
          CERT_KEY=/tmp/cert_key.pem
          openssl genrsa -out $CERT_KEY 2048
          
          # יצירת או הורדת signing files עם ה-key החדש
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --platform IOS \
            --certificate-key=@file:$CERT_KEY \
            --create
          
          # הוספת certificates
          keychain add-certificates
          
          # שימוש ב-profiles
          xcode-project use-profiles

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Flutter build IPA
        script: |
          flutter build ipa --release --build-number=1

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com  # שנה למייל שלך!
        notify:
          success: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true