workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gilad.pklGuide
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
    scripts:
      # התקנת Flutter packages
      - name: Get Flutter packages
        script: |
          flutter pub get

      # ניקוי והכנה
      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
          flutter clean
          flutter pub get

      # התקנת CocoaPods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      # הגדרת Code Signing
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      # בנייה
      - name: Flutter build IPA
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" 2>/dev/null || echo 0) + 1))
          
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true