workflows:
  ios-dev-build:
    name: iOS Development Build
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development
        bundle_identifier: com.gilad.pklGuide
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
        APP_STORE_CONNECT_APPLE_ID: "giladsh22@gmail.com"  # שנה למייל שלך!

    scripts:
      # התקנת Flutter dependencies
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      # עדכון Bundle ID
      - name: Set Bundle ID
        script: |
          cd ios
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      # הגדרת Code Signing אוטומטית
      - name: Set up code signing settings on Xcode
        script: |
          xcode-project use-profiles

      # התקנת CocoaPods
      - name: Install pods
        script: |
          cd ios && pod install

      # בנייה
      - name: Flutter build ipa
        script: |
          cd $CM_BUILD_DIR
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false