workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Setup code signing
        script: |
          # אתחול keychain
          keychain initialize
          
          # הורדת signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --platform IOS
          
          # הוספה ל-keychain
          keychain add-certificates
          
          # שימוש ב-profiles
          xcode-project use-profiles \
            --project ios/Runner.xcodeproj \
            --targets Runner

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Flutter build IPA
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" 2>/dev/null || echo 0) + 1))
          
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true