workflows:
  ios-dev-build:
    name: iOS Development Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
        APP_STORE_CONNECT_APPLE_ID: "giladsh22@gmail.com"

    scripts:
      # התקנת Flutter dependencies
      - name: Get Flutter packages
        script: |
          flutter pub get

      # ניקוי והכנת iOS
      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods
          rm -rf .symlinks
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/Flutter.podspec
          rm -rf Podfile.lock
          cd ..
          flutter clean
          flutter pub get

      # עדכון build number
      - name: Set build number
        script: |
          cd ios
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      # התקנת CocoaPods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      # בנייה
      - name: Flutter build iOS
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/**/*.app
      - build/ios/**/*.dSYM

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true