workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gilad.pklGuide
      vars:
        APP_STORE_APPLE_ID: "giladsh22@gmail.com"
        BUNDLE_ID: "com.gilad.pklGuide"

    scripts:
      # התקנת Flutter dependencies
      - name: Get Flutter packages
        script: |
          flutter pub get

      # ניקוי והכנת iOS
      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
          flutter clean
          flutter pub get

      # יצירת Certificates ו-Provisioning Profiles
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      # הוספת Certificates ל-keychain
      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      # הגדרת השימוש ב-profiles
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      # התקנת CocoaPods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      # בנייה לחנות
      - name: Flutter build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "App Store Connect Users"
        submit_to_app_store: false