workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gilad.pklGuide" #5
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
          flutter clean
          flutter pub get
      - name: Fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
           --type IOS_APP_STORE \
           --platform IOS \
           --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Flutter build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/**/*.app
      - build/ios/**/*.dSYM
    publishing:
      email:
        recipients:
          - giladsh22@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration  # זה משתמש בשם מה-integrations
        submit_to_testflight: true
        beta_groups:
          - "App Store Connect Users"  # ודא שקבוצה זו קיימת ב-App Store Connect
        submit_to_app_store: false