workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    integrations:
      app_store_connect: Apple API Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gilad.pklGuide
      vars:
        BUNDLE_ID: "com.gilad.pklGuide"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Flutter build IPA
        script: |
          flutter build ipa --release --build-number=1

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - myName@gmail.com  # שנה!
        notify:
          success: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true