name: pkl_guide
description: "אפליקציית ערכת הדרכה למדריך"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+7

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^12.0.0
  flutter_slidable: ^4.0.1
#  flutter_swipable_stack: ^0.1.4 # עוד ספריה לדימוי קל של כרטיסים (או alternative)
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  vibration: ^3.1.4
  audioplayers: ^6.5.1
  provider: ^6.1.5
  flutter_card_swiper: ^7.0.2
  http: ^1.5.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  upgrader: ^12.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/timer_end.mp3
    - assets/data.json


fonts:
  - family: Heebo
    fonts:
      - asset: fonts/Heebo-Regular.ttf
      - asset: fonts/Heebo-Bold.ttf
        weight: 700
      - asset: fonts/Heebo-Light.ttf
        weight: 300


flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/logo12.png"
  branding: "assets/branding_logo.png"

  android_12:
    color: "#ffffff"
    image: "assets/logo12.png"
    branding: "assets/branding_logo.png"



